name: Build plugin
on:
  push:
    tags:
      - '*'
env:
  PLUGIN_NAME: logseq-everforest-theme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }} # folder for zip
          cp icon.svg ${{ env.PLUGIN_NAME }} # move icon
          cp README.md package.json index.html index.js *.css ${{ env.PLUGIN_NAME }} # move build assets
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }} # create zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload zip file
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload package.json
        id: upload_metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.json
          asset_name: package.json
          asset_content_type: application/json
